name: Tests

on: [push, pull_request, workflow_dispatch]

jobs:
  formatting:
    name: Check Black Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Check code formatting with black
      run: |
        black -l 120 --check --diff --color qbuild qbuild/qbuild setup.py
